### ISSUE TITLE
Upgrading tuist version crashes the tool

### ISSUE THREAD

**Issue by shahzadmajeed** [tuist/tuist#4552]
## Describe the bug and the expected behavior

This has happened several time as reported here https://tuistapp.slack.com/archives/C018QG7U7SN/p1652714943266129. Tuist starts crashing and responds every command with an error like `[1]          41703  killed            tuist generate`

## Reproduction steps

Steps to reproduce the bug:

1. Use an older version of Tuist
2. Run `tuist update`
3. Run any tuist command in your tuist project
4. It will produce an error like `[1]          41703  killed            command_you_ran`

### Error screenshots
<img width="903" alt="Screen Shot 2022-06-13 at 11 15 40 AM" src="https://user-images.githubusercontent.com/1209459/173390829-48003425-f39c-4245-8f1b-0ed855a60d54.png">

__Please ignore zoom behind the terminal__

### Additional context

- macOS version: 12.4 macOS Monterey
- Tuist version: 3.6.0
- Xcode version: 13.4.1

I'm using M1 Silicon machine. See above slack thread for more context.

**Comment by icedice** [comment]
I'm seeing this too. While being extremely annoying with a tool thats is frequently updated (good thing...) it easily solved by restarting the machine...

**Comment by danyf90** [comment]
Got the same error today after updating to 3.7.0 👀

**Comment by danyf90** [comment]
Note: if you don't want to restart, reinstalling it using the script should fix it: `curl -Ls https://install.tuist.io | bash`

**Comment by ezraberch** [comment]
I can't reproduce this myself (M1-only issue?), but this looks like an OS security feature killing the process. There should be a Console log message when this happens.

We may be able to fix this by having `tuist update` delete the old `tuistenv` first rather than just overwriting it.

**Comment by fortmarek** [comment]
> delete the old tuistenv first rather than just overwriting it.

Worth a try, do you want to try implementing this?

**Comment by shahzadmajeed** [comment]
Hi, 

Upgrading to 3.8.0 still crashed Tuist. However install it directly with bash script `curl -Ls https://install.tuist.io | bash` fixed it.

See screenshot for 3.8.0 below

![Screen Shot 2022-07-05 at 3 52 49 PM](https://user-images.githubusercontent.com/1209459/177406103-2558fbb0-ef32-4157-8490-f53022b41146.png)

**Comment by shahzadmajeed** [comment]
Hi,

Upgrading to 3.8.0 still crashed Tuist. However install it directly with bash script curl -Ls https://install.tuist.io | bash fixed it.

**Comment by ezraberch** [comment]
> Upgrading to 3.8.0 still crashed Tuist.

This is expected.

#4579 is part of 3.8.0. Updating from 3.7.0 to 3.8.0 uses the 3.7.0 code. The fix will apply to any update from 3.8.0 or later to a future version.

**Comment by shahzadmajeed** [comment]
Got it. Sorry for false alarm
