### ISSUE TITLE
Can't get Realm to work as a dependency with Tuist

### ISSUE THREAD

**Issue by freak4pc** [tuist/tuist#5816]
### What happened?

Created a barebones project with no sources which only does `import RealmSwift` and uses https://github.com/realm/realm-swift.git as a dependency

### How do we reproduce it?

1. Unzip reproduction - [RealmRepro.zip](https://github.com/tuist/tuist/files/13993101/RealmRepro.zip)
2. tuist fetch & tuist generate
3. Try to build `MyAppKit` target

### Error log

```

Showing Recent Errors Only
SwiftEmitModule normal arm64 Emitting\ module\ for\ MyAppKitKit (in target 'MyAppKitKit' from project 'MyApp')
    cd /Users/freak4pc/Work/RealmRepro
    builtin-swiftTaskExecution -- /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -emit-module -experimental-skip-non-inlinable-function-bodies-without-types /Users/freak4pc/Work/RealmRepro/Derived/Sources/TuistAssets+MyAppKitKit.swift /Users/freak4pc/Work/RealmRepro/Derived/Sources/TuistBundle+MyAppKitKit.swift /Users/freak4pc/Work/RealmRepro/Modules/MyAppKit/Sources/MyAppKit.swift /Users/freak4pc/Library/Developer/Xcode/DerivedData/MyApp-aydoemfwrugwlaeuawcshdmzkash/Build/Intermediates.noindex/MyApp.build/Debug/MyAppKitKit.build/DerivedSources/GeneratedAssetSymbols.swift -target arm64-apple-macos14.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -stack-check -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -I /Users/freak4pc/Library/Developer/Xcode/DerivedData/MyApp-aydoemfwrugwlaeuawcshdmzkash/Build/Products/Debug -F /Users/freak4pc/Library/Developer/Xcode/DerivedData/MyApp-aydoemfwrugwlaeuawcshdmzkash/Build/Products/Debug -no-color-diagnostics -enable-testing -g -module-cache-path /Users/freak4pc/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity\=checked -Onone -D DEBUG -serialize-debugging-options -const-gather-protocols-file /Users/freak4pc/Library/Developer/Xcode/DerivedData/MyApp-aydoemfwrugwlaeuawcshdmzkash/Build/Intermediates.noindex/MyApp.build/Debug/MyAppKitKit.build/Objects-normal/arm64/MyAppKitKit_const_extract_protocols.json -enable-bare-slash-regex -empty-abi-descriptor -validate-clang-modules-once -clang-build-session-file /Users/freak4pc/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -Xcc -working-directory -Xcc /Users/freak4pc/Work/RealmRepro -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift -enable-anonymous-context-mangled-names -Xcc -fmodule-map-file\=/Users/freak4pc/Work/RealmRepro/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/realm-core/src/external/IntelRDFPMathLib20U2/LIBRARY/src/Bid.modulemap -Xcc -fmodule-map-file\=/Users/freak4pc/Work/RealmRepro/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/realm-core/src/external/s2/s2geometry.modulemap -Xcc -fmodule-map-file\=/Users/freak4pc/Work/RealmRepro/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/realm-core/src/module.modulemap -Xcc -fmodule-map-file\=/Users/freak4pc/Work/RealmRepro/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/realm-swift/include/module.modulemap -Xcc -ivfsstatcache -Xcc /Users/freak4pc/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/macosx14.2-23C53-df0db8920d7ae99241a1bc0f08d2dced.sdkstatcache -Xcc -I/Users/freak4pc/Library/Developer/Xcode/DerivedData/MyApp-aydoemfwrugwlaeuawcshdmzkash/Build/Intermediates.noindex/MyApp.build/Debug/MyAppKitKit.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/freak4pc/Library/Developer/Xcode/DerivedData/MyApp-aydoemfwrugwlaeuawcshdmzkash/Build/Intermediates.noindex/MyApp.build/Debug/MyAppKitKit.build/MyAppKitKit-generated-files.hmap -Xcc -I/Users/freak4pc/Library/Developer/Xcode/DerivedData/MyApp-aydoemfwrugwlaeuawcshdmzkash/Build/Intermediates.noindex/MyApp.build/Debug/MyAppKitKit.build/MyAppKitKit-own-target-headers.hmap -Xcc -I/Users/freak4pc/Library/Developer/Xcode/DerivedData/MyApp-aydoemfwrugwlaeuawcshdmzkash/Build/Intermediates.noindex/MyApp.build/Debug/MyAppKitKit.build/MyAppKitKit-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/freak4pc/Library/Developer/Xcode/DerivedData/MyApp-aydoemfwrugwlaeuawcshdmzkash/Build/Intermediates.noindex/MyApp.build/Debug/MyAppKitKit.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/freak4pc/Library/Developer/Xcode/DerivedData/MyApp-aydoemfwrugwlaeuawcshdmzkash/Build/Intermediates.noindex/MyApp.build/Debug/MyAppKitKit.build/MyAppKitKit-project-headers.hmap -Xcc -I/Users/freak4pc/Library/Developer/Xcode/DerivedData/MyApp-aydoemfwrugwlaeuawcshdmzkash/Build/Products/Debug/include -Xcc -I/Users/freak4pc/Library/Developer/Xcode/DerivedData/MyApp-aydoemfwrugwlaeuawcshdmzkash/Build/Intermediates.noindex/MyApp.build/Debug/MyAppKitKit.build/DerivedSources-normal/arm64 -Xcc -I/Users/freak4pc/Library/Developer/Xcode/DerivedData/MyApp-aydoemfwrugwlaeuawcshdmzkash/Build/Intermediates.noindex/MyApp.build/Debug/MyAppKitKit.build/DerivedSources/arm64 -Xcc -I/Users/freak4pc/Library/Developer/Xcode/DerivedData/MyApp-aydoemfwrugwlaeuawcshdmzkash/Build/Intermediates.noindex/MyApp.build/Debug/MyAppKitKit.build/DerivedSources -Xcc -DDEBUG\=1 -module-name MyAppKitKit -disable-clang-spi -target-sdk-version 14.2 -target-sdk-name macosx14.2 -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/local/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -plugin-path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/lib/swift/host/plugins -emit-module-doc-path /Users/freak4pc/Library/Developer/Xcode/DerivedData/MyApp-aydoemfwrugwlaeuawcshdmzkash/Build/Intermediates.noindex/MyApp.build/Debug/MyAppKitKit.build/Objects-normal/arm64/MyAppKitKit.swiftdoc -emit-module-source-info-path /Users/freak4pc/Library/Developer/Xcode/DerivedData/MyApp-aydoemfwrugwlaeuawcshdmzkash/Build/Intermediates.noindex/MyApp.build/Debug/MyAppKitKit.build/Objects-normal/arm64/MyAppKitKit.swiftsourceinfo -emit-objc-header-path /Users/freak4pc/Library/Developer/Xcode/DerivedData/MyApp-aydoemfwrugwlaeuawcshdmzkash/Build/Intermediates.noindex/MyApp.build/Debug/MyAppKitKit.build/Objects-normal/arm64/MyAppKitKit-Swift.h -serialize-diagnostics-path /Users/freak4pc/Library/Developer/Xcode/DerivedData/MyApp-aydoemfwrugwlaeuawcshdmzkash/Build/Intermediates.noindex/MyApp.build/Debug/MyAppKitKit.build/Objects-normal/arm64/MyAppKitKit-master-emit-module.dia -emit-dependencies-path /Users/freak4pc/Library/Developer/Xcode/DerivedData/MyApp-aydoemfwrugwlaeuawcshdmzkash/Build/Intermediates.noindex/MyApp.build/Debug/MyAppKitKit.build/Objects-normal/arm64/MyAppKitKit-master-emit-module.d -o /Users/freak4pc/Library/Developer/Xcode/DerivedData/MyApp-aydoemfwrugwlaeuawcshdmzkash/Build/Intermediates.noindex/MyApp.build/Debug/MyAppKitKit.build/Objects-normal/arm64/MyAppKitKit.swiftmodule -emit-abi-descriptor-path /Users/freak4pc/Library/Developer/Xcode/DerivedData/MyApp-aydoemfwrugwlaeuawcshdmzkash/Build/Intermediates.noindex/MyApp.build/Debug/MyAppKitKit.build/Objects-normal/arm64/MyAppKitKit.abi.json

<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Realm/Realm.h"
        ^
/Users/freak4pc/Work/RealmRepro/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/realm-swift/include/Realm/Realm.h:21:9: error: 'Realm/RLMArray.h' file not found
#import <Realm/RLMArray.h>
        ^
/Users/freak4pc/Work/RealmRepro/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/realm-swift/include/Realm/Realm.h:21:9: note: did not find header 'RLMArray.h' in framework 'Realm' (loaded from '/Users/freak4pc/Library/Developer/Xcode/DerivedData/MyApp-aydoemfwrugwlaeuawcshdmzkash/Build/Products/Debug')
#import <Realm/RLMArray.h>
        ^
<unknown>:0: error: could not build Objective-C module 'Realm'

/Users/freak4pc/Work/RealmRepro/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/realm-swift/include/Realm/Realm.h:21:9: 'Realm/RLMArray.h' file not found

Could not build Objective-C module 'Realm'

```

### macOS version

14.1

### Tuist version

3.4.0

### Xcode version

15.2

**Comment by dogo** [comment]
I'm using Realm in my pet project

https://github.com/dogo/swdestiny-trades/blob/develop/Tuist/ProjectDescriptionHelpers/Target.swift
https://github.com/dogo/swdestiny-trades/blob/develop/Tuist/Package.swift

**Comment by freak4pc** [comment]
> I'm using Realm in my pet project
> 
> 
> 
> https://github.com/dogo/swdestiny-trades/blob/develop/Tuist/ProjectDescriptionHelpers/Target.swift
> 
> https://github.com/dogo/swdestiny-trades/blob/develop/Tuist/Package.swift

You seem to be using it as xcframework, which I could do but prefer not to, unless I have to.

**Comment by kapitoshka438** [comment]
> > I'm using Realm in my pet project
> > https://github.com/dogo/swdestiny-trades/blob/develop/Tuist/ProjectDescriptionHelpers/Target.swift
> > https://github.com/dogo/swdestiny-trades/blob/develop/Tuist/Package.swift
> 
> You seem to be using it as xcframework, which I could do but prefer not to, unless I have to.

@freak4pc [https://github.com/tuist/tuist/issues/3928#issuecomment-1871644383](this trick) did it for me.

**Comment by freak4pc** [comment]
That worked! Thank you @kapitoshka438 🔥 🚀 
@pepicrft Feel free to close it unless you want to use this info

**Comment by fortmarek** [comment]
Closing as a duplicate of: https://github.com/tuist/tuist/issues/3928

You can follow the progress for a fix for this here: https://github.com/tuist/tuist/pull/5887

**Comment by amarcadet** [comment]
It's worth noting that something has changed on the Realm package between 10.45.0 and 10.46.0.

I pinned the version to 10.45.0 in my project to circumvent the error.

**Comment by kapitoshka438** [comment]
Realm 10.45.3 works but 10.46.0 doesn't. But I agree that issues with various Objective C dependencies should be solved in general.

**Comment by thebarndog** [comment]
@kapitoshka438 if that's true then [this](https://github.com/realm/realm-swift/compare/v10.45.3...v10.46.0) should provide the answer somewhere but I can't say that I see anything that would cause this.

@fortmarek can confirm this is still happening all the way up to the latest release for Realm and with the correct header search paths, which should be `$(SRCROOT)/Tuist/.build/checkouts/realm-swift/include`

**Comment by kapitoshka438** [comment]
@thebarndog something was fixed in later Realm versions. We are successfully using Realm 10.48.1 without any issues, with no workarounds for headers search paths and others

**Comment by thebarndog** [comment]
@kapitoshka438 I'm on 10.52.2, doesn't work for that but 10.48.1 did so I'm pinning to that 😅
