### ISSUE TITLE
Tuist 4.33.0 includes and resolved Swift packages within modules

### ISSUE THREAD

**Issue by danibachar** [tuist/tuist#7064]
### What happened?

Attached a reproducible example of the issue
Using Tuist 4.33.0, we are facing Tuist rtying to resolve and handle unrelated Swift Packages (i.e. Package.swift) files that are included in the repository.

[tuist-4.33.zip](https://github.com/user-attachments/files/17759137/tuist-4.33.zip)

Notice the weird UI here in the Image, where I have a hidden fixture (lets say for testing purposes), and for some reason after a generation Tuist creates a project/workspace that consider those Pacakges as part of the project.

<img width="1287" alt="Screenshot 2024-11-14 at 4 26 05 PM" src="https://github.com/user-attachments/assets/ca85e9dd-c5b2-4944-ac1d-8365c0e6d0ba">

This behaviour is different then Tuist 4.26.0

### How do we reproduce it?

1) Download the attached zip prject.
2) Unzip it and cd into the main folder
3) run `tuist install && tuist generate` and notice the weird project that is generated

Using --no-binary-cache on generation would remove the package resolution, but still you'd see the project consider that hidden folder as a swift package

### Error log

If ill try to run some xcodebuild commands on the generated workspace/project i will get errors such as:
Command :
```
xcodebuild -workspace Tuist4.33.xcworkspace -scheme tuist-4.33 -destination 'platform=iOS'  -skipMacroValidation clean build
```

Full output + error
```sh
danielbac@ZG14839 tuist-4.33 % xcodebuild -workspace Tuist4.33.xcworkspace -scheme tuist-4.33 -destination 'platform=iOS'  -skipMacroValidation clean build
Command line invocation:
    /Applications/Xcode-15.4.0.app/Contents/Developer/usr/bin/xcodebuild -workspace Tuist4.33.xcworkspace -scheme tuist-4.33 -destination platform=iOS -skipMacroValidation clean build

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

Resolve Package Graph
Source files for target .HiddenModule should be located under 'Sources/.HiddenModule', 'Sources', or a custom sources path can be set with the 'path' property in Package.swiftSource files for target .HiddenModuleTests should be located under 'Tests/.HiddenModuleTests', 'Tests', or a custom sources path can be set with the 'path' property in Package.swifttarget '.HiddenModule' referenced in product '.HiddenModule' is empty

Resolved source packages:
  XcodeProj: https://github.com/tuist/XcodeProj.git @ 8.15.0
  Stencil: https://github.com/kylef/Stencil.git @ 0.15.1
  AEXML: https://github.com/tadija/AEXML.git @ 4.6.1
  .HiddenModule: /Users/danielbac/Documents/tuist-4.33/modules/tuist-4.33/.fixtures/modules/.HiddenModule
  PathKit: https://github.com/kylef/PathKit.git @ 1.0.1
  cmark-gfm: https://github.com/apple/swift-cmark.git @ 0.5.0
  swift-argument-parser: https://github.com/apple/swift-argument-parser @ 1.2.3
  swift-markdown: https://github.com/apple/swift-markdown.git @ 0.5.0
  Cuckoo: https://github.com/Brightify/Cuckoo.git @ 2.0.10
  swift-syntax: https://github.com/apple/swift-syntax.git @ 509.0.0
  Spectre: https://github.com/kylef/Spectre.git @ 0.10.1
  TOMLKit: https://github.com/LebJe/TOMLKit.git @ 0.5.5
  FileKit: https://github.com/nvzqz/FileKit.git @ 6.1.0
  Rainbow: https://github.com/onevcat/Rainbow @ 4.0.1
  swift-format: https://github.com/apple/swift-format.git @ 509.0.0

2024-11-14 16:34:30.037 xcodebuild[32649:18320405] Writing error result bundle to /var/folders/tl/r_4sm5dn09qbr13xs1f64g1r0000gq/T/ResultBundle_2024-14-11_16-34-0030.xcresult
xcodebuild: error: Could not resolve package dependencies:
  target '.HiddenModule' referenced in product '.HiddenModule' is empty
```

### macOS version

14.7.1

### Tuist version

4.33.0

### Xcode version

15.4

**Comment by fortmarek** [comment]
Hey 👋 

I understand the `xcodebuild` command is failing, but that's not really helpful in this case. Can you update the reproducer, so that `tuist generate` includes the `Package.swift` that you wouldn't expect to include?

FWIW, what has changed since `4.26.0` is we don't implicitly ignore hidden files when expanding globs.

The unexpected `Package.swift` is most likely either taken via the `additionalFiles` globs or through the `Workspace.swift` glob. I can't tell exactly because the reproducer is incomplete.

**Comment by danibachar** [comment]
> Hey 👋
> 
> I understand the `xcodebuild` command is failing, but that's not really helpful in this case. Can you update the reproducer, so that `tuist generate` includes the `Package.swift` that you wouldn't expect to include?
> 
> FWIW, what has changed since `4.26.0` is we don't implicitly ignore hidden files when expanding globs.
> 
> The unexpected `Package.swift` is most likely either taken via the `additionalFiles` globs or through the `Workspace.swift` glob. I can't tell exactly because the reproducer is incomplete.

This is exactly what happens, I have a hidden folder with a Package.swift. The annoying thing is that I also have non hidden folders that have a Package.swift files and those are not being resolved.

I have updated the original link of the example, you can see under `.fixtures/modules/.Hidden` is the problematic package. And the Project.swift defintion has the Package.

In addition, I have a new example [tuist-4.33-Module1.zip](https://github.com/user-attachments/files/17779708/tuist-4.33-Module1.zip) - that shows an additional Package.swift file under the same `.fixtures/modules/Module1` that is not resolved by xcode under the same scenario

**Comment by danibachar** [comment]
Here is an image with the same structure when the folder is not hidden
<img width="979" alt="Screenshot 2024-11-15 at 11 50 48 AM" src="https://github.com/user-attachments/assets/f4a459d7-1c05-4240-95f0-c35665e6a786">

**Comment by danibachar** [comment]
Last update, I did find a workaround, which alternate the globs pattern we are setting for the project.
The issue is that for `additionalFiles` globs, there is no smart pattern filtering. So I need to be explicit about files.

This could also be solved by extending the `FileElement` globs to be like the `ResourceFileElement` which I can exclude

I wonder if this should be taken under consideration

**Comment by fortmarek** [comment]
> In addition, I have a new example [tuist-4.33-Module1.zip](https://github.com/user-attachments/files/17779708/tuist-4.33-Module1.zip) - that shows an additional Package.swift file under the same .fixtures/modules/Module1 that is not resolved by xcode under the same scenario

I still can't use your reproducer. When I download it and run `tuist install` and `tuist generate`, I get "`SwiftSyntax` is not a valid configured external dependency". Can you double check the reproducer is valid?

That being said, I'd recommend against using `"**/**/*.*"` as `additionalFiles` as that does pick up files you might not want in Xcode. And it's expected this also picks up `Package.swift` which in turn could lead to Xcode resolving it.

> This could also be solved by extending the FileElement globs to be like the ResourceFileElement which I can exclude

Yes, I do think having `excluding` for `FileElement.glob` would make sense.
