### ISSUE TITLE
Mise Install Broken

### ISSUE THREAD

**Issue by jmonroe** [tuist/tuist#7835]
### What happened?

The most recent release does not have the necessary artifacts to allow Tuist to be installed via Mise as recommended.

```sh
mise install tuist

curl: (56) The requested URL returned error: 404
mise ERROR ~/.local/share/mise/plugins/tuist/bin/download failed
* Downloading tuist release app@0.19.0...
curl: (56) The requested URL returned error: 404
asdf-tuist: Could not download https://github.com/tuist/tuist/releases/download/app@0.19.0/tuist.zip
mise ERROR failed to install asdf:tuist@app@0.19.0
mise ERROR ~/.local/share/mise/plugins/tuist/bin/download exited with non-zero status: exit code 1
mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
````

### How do we reproduce it?

1. Open the command line and run `miss install tuist`
2. Observe that the install fails because the twist.zip artifact can not be found.

### Error log

```sh
mise install tuist
curl: (56) The requested URL returned error: 404
mise ERROR ~/.local/share/mise/plugins/tuist/bin/download failed
* Downloading tuist release app@0.19.0...
curl: (56) The requested URL returned error: 404
asdf-tuist: Could not download https://github.com/tuist/tuist/releases/download/app@0.19.0/tuist.zip
mise ERROR failed to install asdf:tuist@app@0.19.0
mise ERROR ~/.local/share/mise/plugins/tuist/bin/download exited with non-zero status: exit code 1
mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
```

### macOS version

15.6

### Tuist version

app@0.19.0

### Xcode version

16.4

**Comment by pepicrft** [comment]
@jmonroe could you try to run `mise plugins update tuist` and run the install command again?

**Comment by MisnikovRoman** [comment]
@pepicrft I had the same problem and `mise plugins update tuist` helped to fix problem

**Comment by pepicrft** [comment]
Thanks for the heads up. I turned out that we pushed a tag by mistake and that caused the installation to break.

**Comment by PaulTaykalo** [comment]
@pepicrft 
I'm a bit confused. Will there be new releases with valid tuist.zip artifacts?
there were to releases since https://github.com/tuist/tuist/releases/tag/4.55.6

Or should we migrate for using homebrew installations?

**Comment by fortmarek** [comment]
> I'm a bit confused. Will there be new releases with valid tuist.zip artifacts?
there were to releases since https://github.com/tuist/tuist/releases/tag/4.55.6

`4.55.6` is still the latest CLI release. The other releases are related to the macOS Tuist app.

> Or should we migrate for using homebrew installations?

Is the mise installation still broken for you? You should certainly not have to migrate to using brew.

**Comment by PaulTaykalo** [comment]
Thanks for the update.

Mise installation works fine, since we have `mise.toml` with a specified version. it is just
Some improvements were made

This one specifically https://github.com/tuist/tuist/pull/7825

Which I woul probably like to see in the new release tag.

**Comment by fortmarek** [comment]
Got it 👍 

Yeah, we are working on a new release, but we're underway restructuring things a bit, which is why this one is taking a bit longer. We hope to release a new version by the end of the week 👀

**Comment by havebeenfitz** [comment]
Hi @pepicrft, it seems like the installation is broken every time the app@... tag is the last one, can it be the case? Not sure about the reasons. For brew installation it works fine

**Comment by fortmarek** [comment]
Have you updated the tuist plugin (`mise plugins update tuist`)?

**Comment by havebeenfitz** [comment]
Yes, that didn't help. But setting the global config with `mise use -g tuist@...` did I guess. But I'm still not sure why it happened and why setting the global one helped
